// Generated by CoffeeScript 1.12.8
(function() {
  window.app = angular.module('app', ['ngRoute']);

  app.filter('escape', function() {
    return window.encodeURIComponent;
  });

  app.config(function($routeProvider) {
    $routeProvider.when('/:term?', {
      templateUrl: 'main.html',
      controller: 'main'
    });
    return $routeProvider.otherwise({
      redirectTo: '/'
    });
  });

  app.controller('main', function($scope, $routeParams, $location, queryService) {
    var search;
    $scope.add = function(rad) {
      return $scope.search_bar.insert(rad);
    };
    $scope.term = $routeParams.term || '';
    $scope.status = '';
    $scope.results = [];
    $scope.search_submit = function() {
      return $location.path("/" + $scope.term);
    };
    search = function(term) {
      var xhr;
      $scope.status = 'Searching...';
      xhr = queryService.lookup(term);
      xhr.success(function(data, status) {
        $scope.status = 'Results:';
        return $scope.results = data;
      });
      return xhr.error(function() {
        return $scope.status = 'Error!';
      });
    };
    if ($scope.term) {
      return search($scope.term);
    }
  });

}).call(this);
