// Generated by CoffeeScript 1.4.0
(function() {

  window.app = angular.module('app', []);

  app.filter('escape', function() {
    return window.encodeURIComponent;
  });

  app.controller('main', function($scope, queryService) {
    $scope.add = function(rad) {
      return $scope.search_bar.insert(rad);
    };
    $scope.status = '';
    $scope.results = [];
    $scope.search_submit = function(term) {
      var xhr;
      $scope.status = 'Searching...';
      xhr = queryService.lookup(term);
      xhr.success(function(data, status) {
        if (status === 200) {
          $scope.status = 'Results:';
          return $scope.results = data;
        } else {
          return $scope.status = 'Error!';
        }
      });
      xhr.error(function() {
        return $scope.status = 'Error!';
      });
      return xhr["finally"](function() {
        return $scope.searching = False;
      });
    };
    $scope.examples = ['[儿田]法', '[罒]す', '[乃]う', '[韭][火]', '飛び[]る'];
    return $scope.search_example = function(str) {
      $scope.search_bar.set(str);
      return $scope.search_submit(str);
    };
  });

}).call(this);
