// Generated by CoffeeScript 1.4.0
(function() {

  app.service('queryService', function($http) {
    this.lookup = function(search_term) {
      return $http.get('http://kantan.wtf.im:4000/' + search_term);
    };
    return this;
  });

}).call(this);
