// Generated by CoffeeScript 1.9.3
(function() {
  app.service('queryService', function($http) {
    this.lookup = function(search_term) {
      return $http.get('http://kantan.nonze.ro:4000/' + search_term);
    };
    return this;
  });

}).call(this);
